name: CI

on:
  - push

jobs:
  windows-ia32:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install packages
        run: npm install

      - name: Build
        run: npx electron-builder --win --ia32  --publish never
      
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: windows-ia32
          path: dist/redish-app-2
          if-no-files-found: error